-- INSERT INTO users (FirstName, LastName, Address, Email, Password, ImageUrl, UserType, createdAt,updatedAt) VALUES
-- ('Iheb', 'ghdifi', '120 city jassmin', 'ihebghdi@live.fr', 'RAMIRAMI', 'https://cdn.mos.cms.futurecdn.net/ardTWtasUnsun7e9F7xYsU-1200-80.jpg', 'client', NOW(),NOW()),
-- ('Ramy', 'sassi', '120 city jassmin', 'ramysa@live.fr', 'RAMIRAMI', 'https://i0.wp.com/www.moyens.net/wp-content/uploads/2021/11/1636254757_219_Comment-utiliser-mon-avatar-Facebook-sur-WhatsApp.jpg?resize=700%2C1515&ssl=1', 'client', NOW(),NOW()),
-- ('Aziz', 'Lajnef', '120 city jassmin', 'azyzzven@live.fr', 'RAMIRAMI', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXmftdvgEnKtracmKw2_fsoyxAPZJD1BdujHXz6bgytTF-pEtpASfVEO63qD0E-T_o4vI&usqp=CAU', 'client', NOW(),NOW()),
-- ('Dhia', 'Hamouda', '120 city jassmin', 'dhiaham@live.fr', 'RAMIRAMI', 'https://lifehacker.com/imagery/articles/01HF2GKNRQZ4MN1YA639Q53NQV/hero-image.fill.size_1248x702.v1699833590.png', 'client', NOW(),NOW()),
-- ('Amin', 'oueslaty', '120 city jassmin', 'amineouse@live.fr', 'RAMIRAMI', 'https://pbs.twimg.com/media/EYVxlOSXsAExOpX.jpg', 'client', NOW(),NOW()),
-- ('Coffee', 'Hos', '120 city jassmin', 'houssem@live.fr', 'RAMIRAMI', 'https://scontent.ftun2-2.fna.fbcdn.net/v/t39.30808-1/279660318_5147562128623077_3464542306251958250_n.jpg?stp=c0.2.60.60a_cp0_dst-jpg_p60x60&_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_ohc=XjHS24v2KqsQ7kNvgFSlhBs&_nc_ht=scontent.ftun2-2.fna&oh=00_AYCi4ExX6z31K_IruAjGUPzKLeVkMLeazlamWFEYZ8wRvQ&oe=66525C6D', 'coffee', NOW(),NOW());


-- INSERT INTO prods(name, price, imgUrl, description, category, createdAt,updatedAt) VALUES
-- ('expresso', 3, 'https://bpholdings.be/breakpoint/wp-content/uploads/2020/06/1_fullsize.jpg', 'express4 or short coffee is a very full-bodied coffee with a strong aroma, obtained by percolation under high pressure, that is- i.e. by quickly passing hot water under a pressure of 9 bar through roasted and finely ground coffee.', 'coffee', NOW(),NOW()),
-- ('double coffe', 3, 'https://www.breville.com/content/dam/breville-brands/coffeehub/language-masters/fr_ca/recipes/recipe-hero-stills/Recipes_Banner12_1200x1200_LongBlack.jpeg', 'longue coffee is a very full-bodied coffee with a strong aroma, obtained by percolation under high pressure, that is- i.e. by quickly passing hot water under a pressure of 9 bar through roasted and finely ground coffee.', 'coffee' , NOW(),NOW()),
-- ('cappuccino coffe', 4, 'https://www.nescafe.com/nz/sites/default/files/2023-04/FullCoffeeCups_738x800_Frothy.png', 'cappuccino coffee is a strong aroma, obtained by percolation under high pressure, that is- i.e. by quickly passing hot water under a pressure of 9 bar through roasted and finely ground coffee.', 'coffee', NOW(),NOW()),
-- ('Frappuccino', 8, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Caramel_Frappuccino.jpg.webp?itok=LqM4c_Zc', 'Frappuccino coffee is a cold coffee, obtained by percolation under high pressure, that is- i.e. by quickly passing hot water under a pressure of 9 bar through roasted and finely ground coffee.', 'coffee' , NOW(),NOW()),
-- ('Pain au chocolat', 2, 'https://www.lesrecettesdevanessa.fr/wp-content/uploads/2021/08/Recette-Pain-Chocolat_les-recettes-de-vanessa.jpg', '(Pain au chocolat) or (chocolate) is a pastry created by the Austrians August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'cake' , NOW(),NOW()),
-- ('croissant', 2, 'https://optimise2.assets-servd.host/bridor-new/production/uploads/59103_side_W.png?w=1200&auto=compress%2Cformat&fit=crop&dm=1655312074&s=efff3ab7abded93884f0a2007dea00c1', 'Croissant is a pastry created by the Austrians August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'cake' , NOW(),NOW()),
-- ('chocolate cake', 5, 'https://img.freepik.com/free-psd/zebra-cakes-isolated-transparent-background_191095-27954.jpg?size=338&ext=jpg&ga=GA1.1.87170709.1707782400&semt=ais', 'chocolate cake is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'cake' , NOW(),NOW()),
-- ('Vanille cake', 5, 'https://p1.hiclipart.com/preview/552/54/403/slice-of-vanilla-cake-png-clipart.jpg', 'Vanille cake is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'cake' , NOW(),NOW()),
-- ('Fraise cake', 5, 'https://e7.pngegg.com/pngimages/210/757/png-clipart-cheesecake-fruitcake-cream-pizza-bakery-cake-batter-food-strawberries.png', 'Fraise cake is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'cake' , NOW(),NOW()),
-- ('orange jus', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP0wlofa40do5gOjKfGc-04qQUr7KyIvBBoqg-8bMIkg&s', 'orange jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'drink' , NOW(),NOW()),
-- ('fraise jus', 5, 'https://e7.pngegg.com/pngimages/814/266/png-clipart-strawberry-juice-smoothie-orange-drink-health-shake-smoothies-non-alcoholic-beverage-fruit.png', 'fraise jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'drink' , NOW(),NOW()),
-- ('banane jus', 5, 'https://e7.pngegg.com/pngimages/84/384/png-clipart-juice-smoothie-banana-banana-juice-food-fruit.png', 'banane jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'drink' , NOW(),NOW()),
-- ('coctaile jus', 9, 'https://png.pngtree.com/png-clipart/20190604/original/pngtree-fruits-and-fruit-juices-png-image_1212500.jpg', 'coctaile jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the' ,'drink' ,NOW(),NOW())



-- INSERT INTO reviews (stars, comment, createdAt,updatedAt) VALUES
-- (2, 'nice coffee, I like it', NOW(),NOW()),
-- (2, 'nice coffee, I like it', NOW(),NOW()),
-- (2, 'nice coffee, I like it', NOW(),NOW()),
-- (2, 'nice coffee, I like it', NOW(),NOW()),
-- (2, 'nice coffee, I like it', NOW(),NOW());
