-- -- INSERT INTO users (FirstName, LastName, Address, Email, Password, ImageUrl, UserType, createdAt,updatedAt) VALUES
-- -- ('Iheb', 'ghdifi', '120 city jassmin', 'ihebghdi@live.fr', 'RAMIRAMI', 'https://cdn.mos.cms.futurecdn.net/ardTWtasUnsun7e9F7xYsU-1200-80.jpg', 'client', NOW(),NOW()),
-- -- ('Ramy', 'sassi', '120 city jassmin', 'ramysa@live.fr', 'RAMIRAMI', 'https://i0.wp.com/www.moyens.net/wp-content/uploads/2021/11/1636254757_219_Comment-utiliser-mon-avatar-Facebook-sur-WhatsApp.jpg?resize=700%2C1515&ssl=1', 'client', NOW(),NOW()),
-- -- ('Aziz', 'Lajnef', '120 city jassmin', 'azyzzven@live.fr', 'RAMIRAMI', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXmftdvgEnKtracmKw2_fsoyxAPZJD1BdujHXz6bgytTF-pEtpASfVEO63qD0E-T_o4vI&usqp=CAU', 'client', NOW(),NOW()),
-- -- ('Dhia', 'Hamouda', '120 city jassmin', 'dhiaham@live.fr', 'RAMIRAMI', 'https://lifehacker.com/imagery/articles/01HF2GKNRQZ4MN1YA639Q53NQV/hero-image.fill.size_1248x702.v1699833590.png', 'client', NOW(),NOW()),
-- -- ('Amin', 'oueslaty', '120 city jassmin', 'amineouse@live.fr', 'RAMIRAMI', 'https://pbs.twimg.com/media/EYVxlOSXsAExOpX.jpg', 'client', NOW(),NOW()),
-- -- ('Coffee', 'Hos', '120 city jassmin', 'houssem@live.fr', 'RAMIRAMI', 'https://scontent.ftun2-2.fna.fbcdn.net/v/t39.30808-1/279660318_5147562128623077_3464542306251958250_n.jpg?stp=c0.2.60.60a_cp0_dst-jpg_p60x60&_nc_cat=103&ccb=1-7&_nc_sid=5f2048&_nc_ohc=XjHS24v2KqsQ7kNvgFSlhBs&_nc_ht=scontent.ftun2-2.fna&oh=00_AYCi4ExX6z31K_IruAjGUPzKLeVkMLeazlamWFEYZ8wRvQ&oe=66525C6D', 'coffee', NOW(),NOW());


-- INSERT INTO prods(name, price, imgUrl, description, category, createdAt,updatedAt) VALUES
-- ('Iced Mocha', 8, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Iced_Mocha.jpg.webp?itok=F1akXZw4', 'A rich, full-bodied espresso, blended with chocolate-flavored syrup, milk and ice, topped with sweetened whipped cream.', 'coffee', NOW(),NOW()),
-- ('Iced Brown Sugar Oat Shaken Espresso', 7, 'https://www.breville.com/content/dam/breville-brands/coffeehub/language-masters/fr_ca/recipes/recipe-hero-stills/Recipes_Banner12_1200x1200_LongBlack.jpeg', 'longue coffee is a very full-bodied coffee with a strong aroma, obtained by percolation under high pressure, that is- i.e. by quickly passing hot water under a pressure of 9 bar through roasted and finely ground coffee.', 'coffee' , NOW(),NOW()),
-- ('cappuccino coffe', 4, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Latte_OPT2.jpg.webp?itok=u6SiNyqd', 'The intensity of our espresso meets the sweetness of steamed milk, all covered with a thin layer of milk foam.', 'coffee', NOW(),NOW()),
-- ('Americano', 5, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Americano.jpg.webp?itok=Usrs12L0','Shots d'espresso couverts d'eau chaude, générant une fine couche crémeuse.', 'coffee' , NOW(),NOW()),
-- ('Café Filtre', 3, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Fresh_Brewed_Coffee.jpg.webp?itok=tbMOpHsF','Medium roast coffee, smooth, balanced and rich in flavor.', 'coffee' , NOW(),NOW()),
-- ('Espresso', 3, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Espresso.jpg.webp?itok=Hni2y6HF','A shot of espresso. Nothing more.', 'coffee' , NOW(),NOW()),

-- ('Iced Latte', 8, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-03/SBX_DEL_1200x1200_Iced_Cafe_Latte.jpg.webp?itok=5d5zLK5Y','The intensity of our espresso meets the sweetness of milk, served covered with ice cubes.', 'coffee' , NOW(),NOW()),
-- ('Croissant au beurre', 2, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2020-07/Starbucks_FR_Deliveroo_1200x1200_Croissant_au_Beurre.jpg.webp?itok=KUvakGLy', 'Pure butter, origin France', 'cake' , NOW(),NOW()),
-- ('Pain au chocolat', 2, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2020-07/Starbucks_FR_Deliveroo_1200x1200_Pain_au_Chocolat.jpg.webp?itok=_33ceFkR', 'Pur beurre, origine France', 'cake' , NOW(),NOW()),
-- ('Cinnamon Roll', 3, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2022-10/Cinnamon%20Roll%20Cuit%20sur%20Place.jpg.webp?itok=ZfcTuAsh', 'Roulé à la cannelle avec un nappage au sucre', 'cake' , NOW(),NOW()),
-- ('Chocolate Roll', 5, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2023-11/SBX_DEL_1200x1200_Chocolate_Roll.jpg.webp?itok=q6ty3xcJ', 'Roulé au chocolat avec éclat de noisette .', 'cake' , NOW(),NOW()),

-- ('Pistachio Square', 5, 'https://www.starbucks.fr/sites/starbucks-fr/files/styles/c04_image_text_grid_600x600/public/2024-05/SBX_DEL_1200x1200_Pistachio_Square.jpg.webp?itok=tRh2rQjn', 'Brownie à la pistache avec éclats de pistache', 'cake' , NOW(),NOW()),

-- -- ('orange jus', 5, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQP0wlofa40do5gOjKfGc-04qQUr7KyIvBBoqg-8bMIkg&s', 'orange jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'drink' , NOW(),NOW()),
-- -- ('fraise jus', 5, 'https://e7.pngegg.com/pngimages/814/266/png-clipart-strawberry-juice-smoothie-orange-drink-health-shake-smoothies-non-alcoholic-beverage-fruit.png', 'fraise jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'drink' , NOW(),NOW()),
-- -- ('banane jus', 5, 'https://e7.pngegg.com/pngimages/84/384/png-clipart-juice-smoothie-banana-banana-juice-food-fruit.png', 'banane jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the first croissants that they sold between 1837 and 1839 in their Viennese Bakery in Paris2.', 'drink' , NOW(),NOW()),
-- -- ('coctaile jus', 9, 'https://png.pngtree.com/png-clipart/20190604/original/pngtree-fruits-and-fruit-juices-png-image_1212500.jpg', 'coctaile jus is a pastry created with chocolate August Zang and Ernest Schwarzer1. It is in fact a chocolate version of the croissant made with brioche dough and derived from the' ,'drink' ,NOW(),NOW())




-- -- INSERT INTO reviews (stars, comment, createdAt,updatedAt) VALUES
-- -- (2, 'I like this product it's really smooth and has an after taste of chocolate. Service was brilliant and the coffee was delivered the day after I ordered it and was ground perfectly for the Cafetiere., I like it', NOW(),NOW()),
-- -- (5, ' I recently purchased Kopi Luwak as a gift for my Father, he had been wanting to try it for a long time and was so excited when he opened it. You could smell the coffee through the wrapping paper and when he tried it, he loved it. I will definitely be recommending this coffee to others and recommend they purchase from your website as the delivery and service was brilliant. Many thanks., I like it', NOW(),NOW()),
-- -- (3, 'I find, in life, you generally get what you pay for - and this is no exception. It won't replace my day-to-day coffee, but it's well worth splashing out on if I fancy some caffeine based, self-indulgence and luxury. Guests who try it are always sceptical, but after tasting, unanimously agree it has a superior, bitter-free taste than the run of the mill stuff., I like it', NOW(),NOW()),
-- -- (3, 'Thought we would try a different coffee this time - glad we did, I like it', NOW(),NOW()),
-- -- (2, 'I bought this coffee as a treat for us all to have after our Boxing Day dinner party. The coffee was delivered really quickly and the smell as I opened the bag was fabulous. It went down a treat with all my guests, and of course the story of how it is produced went down a storm. I will definately be using this site again. Fantastic service and the coffee is amazing. Highly recommended, I like it', NOW(),NOW());
-- -- (4, 'Brought some Kopi Luwak to enjoy on Christmas day. Didn't order until late but even with the standard postage the coffee arrived in time great service. The coffee went down a treat and I'm just about to order some more thank you the love of coffee', NOW(),NOW()),
-- -- (1, 'FOR ME, THIS IS THE BEST OF THE FLAVOURED COFFEES THAT I'VE TRIED. IT FILLS THE WHOLE ROOM WITH THE INTENSE AROMA OF CHOCOLATE.', NOW(),NOW()),
-- -- (5, 'I've been wanting to try this coffee for a long time now and it was definitely worth the wait! It's lovely, much smoother than I thought it would be. I will most definitely be ordering again. The delivery time was brilliant as well. I ordered late on a Thursday night and received it on Saturday, I only paid for standard delivery. I would recommend this coffee and company to anyone. Thank you.', NOW(),NOW()),
-- -- (3, 'A very nice coffee! You must try!.......', NOW(),NOW()),
-- -- (2, 'A lovely chocolate flavoured coffee, I enjoy this one at anytime of day, friends have loved this one to. Only problem they want more, its not a problem for long though, as your service is so quick, dont need to be without!', NOW(),NOW()),
-- -- (2, 'I like so many of those on here, bought the coffee having watched Bucket List. Having endured endless remarks about it being 'Cat Sh*t Coffee', I invited the members of my team to taste. We sat down with our cafetieres and sampled the taste. All I can say is that it is pleasant and well worth the investment. Suffice to say, theloveofcoffee will be getting my next order, their service is remarkable.', NOW(),NOW()),
-- -- (1, ' Well worth the money and a perfect coffee for after a meal in the evening.', NOW(),NOW()),
-- -- (4, ' First heard of this coffee in the film "The Bucket List" Found the coffee to be strong, but smooth with no after taste. Would recommend everyone to try it. Ideal for the special occasions.', NOW(),NOW()),
-- -- (3, ' A lovely cup of herbal tea! - glad we did, I like it', NOW(),NOW()),
-- -- (2, ' Some colleagues had been talking about Kopi Luwak coffee & I thought it would be a nice 'thank you' gift to my parents who look after after my wee dog every day ;o) The coffee arrived the day after I placed the order & the coffee went down a treat with my parents. Thanks to 'The Love of Coffee' for the great service - I will definately use you again & I think you will be receiving an order from my parents too, lol ;o) ', NOW(),NOW()),
-- -- (1, 'Thought we would try a different coffee this time - glad we did, I like it', NOW(),NOW()),
-- -- (5, 'Quite a distinctive taste, definitely worth a try :)', NOW(),NOW()),
-- -- (4, 'Well, what can I say? This coffee just ''hits the spot''. Its great made on a stove-top. Just love it. Really great service as well. I had problems signing in (not TLoC''s fault) and a few attempts later I had still not placed my order. Monday AM, I had an email waiting, asking if there was anything that TLoC could do to help and sure enough my order went through. Unheard-of great service from an online supplier. Thanks. :)', NOW(),NOW()),
-- -- (5, 'Quite a distinctive taste, definitely worth a try :)', NOW(),NOW()),
-- -- (4, 'I bought this coffee after reading reviews.And was delighted with it, very smooth tasting.I was also impressed with the prompt service and would have no hesitation in ordering again.', NOW(),NOW()),
-- -- (2, 'A delicious cup of coffee, the Amaretto adds a nice twist to the flavour.', NOW(),NOW()),
-- -- (5, 'An extremely nice coffee, doesn't have that bitter after taste that some coffees produce. Very pleased with my first ever online order! thumbs up for 'The Love of Coffee'.', NOW(),NOW()),
-- -- (1, 'Quite a distinctive taste, definitely worth a try :)', NOW(),NOW()),
-- -- (2, ' Such a wonderful cup of coffee. :)', NOW(),NOW()),
-- -- (5, ' Having seen this on various cooking programs i was determined to try it. I wasnt disappointed, it has a great and unique flavour and i will be buying more as gifts in the future. Give it a try!!', NOW(),NOW()),
-- -- (3, 'I just HAD to try this coffee! I saw a piece on TV about the making of it and was eager to give it a go! There is something about drinking the most expensive coffee ever ever ever that is really satisfying. The flavour is quite rich and is equally tasty drunk as a latte as when drunk black. Quite smooth with not a hint of a bitter after-taste. I will certainly be buying more. A great talking point at the dinner table!', NOW(),NOW()),
-- -- (5, 'I LOVE Coffee and just had to try this ..... I was not disappointed - Strong flavour but no bitter after taste - I took it into work to share the experience and it was a BIG hit - think a few of my colleagues will be placing and order in the not distance future - Coffee lovers ... give it a go !!!!', NOW(),NOW()),
-- -- (5, ' I bought this coffee as a gift for someone who really knows their coffee and had read about it. Thankfully the recipient shared their gift with me. It was really lovely, something to have on special occassions. I recently bought Bucket List on DVD and spotted the reference to Kopi Luwak coffee.', NOW(),NOW()),
-- -- (4, 'Fantastic customer service and super fast delivery to BFPO - really impressed. The coffee was bought for a present and the packaging looks very polished and professional.', NOW(),NOW()),
-- -- (5, ' Love this coffee, with the perfect hint of strawberry & Cream, its a must. Great service', NOW(),NOW()),
-- -- (5, 'Fabulous aroma, very smooth everyday coffee. This one is definitely my favourite of them all. Enjoyed every moment. :)', NOW(),NOW()),
